STIMULI = ["frequencies", "syllables", "words", "sentences"]

SYLLABLES = ['Aah', 'Air','Bath', 'Cil', 'Coat', 'Cream', 'Flah', 'Ice', 'Low', 'Ohh', 'Pen', 'Plane', 'Pull', 'Purr', 'Rain', 'Range', 'Seh', 'Tub', 'Ven', 'Wer', 'Yeh']

SYLLABLES_WORDS = {
    'Airplane' : ['air', 'plane'],
    'Bathtub' : ['bath', 'tub'],
    'Pencil' : ['pen', 'cil'],
    'Raincoat' : ['rain','coat'],
    'Icecream' : ['ice','cream'],
    'Flower' : ['flah', 'wer'],
    'Yellow' : ['yeh', 'low'],
    'Orange' : ['ohh', 'range'],
    'Purple' : ['purr', 'pull'],
    'Seven' : ['seh', 'ven'],
}

WORDS_S = ['Apple', 'Airplane', 'Bathtub', 'Pencil', 'Raincoat', 'Icecream', 'Flower', 'Yellow', 'Orange', 'Purple', 'Seven']

SIMILAR_SYLLABLES = [
    ['aah', 'yeh'],
    ['air', 'wer'],
    ['cil', 'seh'],
    ['low', 'ohh'],
    ['pen', 'ven'],
    ['plane', 'rain'],
    ['rain', 'range'],
    ['seh', 'yeh']
]

WORDS = [
    'Airplane',
    'Apple',
    'Ball',  
    'Bathe',
    'Bathtub',
    'Black',
    'Blue',
    'Book',
    'Brown',
    'Chair',
    'Comb',
    'Eat',
    'Eight',
    'Five',
    'Flower',
    'Four',
    'Green',
    'Grey',
    'Ice-cream',
    'Light',
    'Nine',
    'One',
    'Orange',
    'Pink',
    'Purple',
    'Raincoat',
    'Read',
    'Red',
    'Ride',
    'Seven',
    'Sit',
    'Six',
    'Smell',
    'Soap',
    'Table',
    'Tan',
    'Three',
    'Throw',
    'Two',
    'Wash',    
    'Wear',
    'White',
    'Write',
    'Yellow'
]

SIMILAR_WORDS = [
    ['apple', 'purple'],
    ['apple', 'table'],
    ['bathe', 'eight'],
    ['book', 'pink'],
    ['chair', 'wear'],
    ['eat', 'sit'],
    ['eight', 'light'],
    ['ice-cream', 'green'],
    ['green', 'three'],
    ['light', 'sit'],
    ['light', 'white'],
    ['one', 'tan'],
    ['purple', 'table'],
    ['read', 'ride'],
    ['read', 'red'],
    ['read', 'three'],
    ['red', 'ride'],
    ['ride', 'write'],
    ['sit', 'six'],
    ['white', 'write']
]

SENTENCES = [
    "All actors use makeup",
    "America is a democratic nation",
    "America is the land of the free",
    "Are you a good driver?",
    "Are you bringing ice cream?",
    "Are you fond of eggplant?",
    "Are you hanging draperies at the windows?",
    "A bookmark is useful",
    "A cube has six sides",
    "A lifesaver should be on every public bathing beach",
    "Bees make honey",
    "Be careful not to break the dish",
    "Boil the egg four minutes",
    "Both of us will go",
    "Breakfast is my favorite meal",
    "Buy some paper for your notebook",
    "Can't you stay a while longer?",
    "Can you blow up the balloon?",
    "Can you dance a jig?",
    "Can you hear the bee buzzing?",
    "Can you hear the rain on the roof?",
    "Can you make good cornbread?",
    "Can you make pancakes?",
    "Can you play the piano?",
    "Can you row a boat?",
    "Can you run this machine?",
    "Can you sew?",
    "Can you stop for a minute?",
    "Can you whistle the tune for me?",
    "Children like to play on haystacks",
    "Children wish on a new moon",
    "Come again",
    "Did someone say something?",
    "Did the boy leave the paper?",
    "Did you enjoy the movie?",
    "Did you feed the goldfish?",
    "Did you get the point?",
    "Did you have an egg for breakfast?",
    "Did you hear the bell?",
    "Did you hear the church bell?",
    "Did you hear the whistle?",
    "Did you hurt your wrist?",
    "Did you leave your name?",
    "Did you like the play?",
    "Did you play football at school?",
    "Did you say something?",
    "Did you see the sign?",
    "Did you win the game?",
    "Does your watch keep good time?",
    "Don't breathe a word to a soul",
    "Don't get near the fire",
    "Don't point your finger",
    "Don't rush me",
    "Don't talk so loud",
    "Do not go beyond the gate",
    "Do you care to go to the movies?",
    "Do you go to church?",
    "Do you have a bookkeeper?",
    "Do you have a car?",
    "Do you have a match?",
    "Do you have a rowboat?",
    "Do you have change for a dollar?",
    "Do you hear better through the loudspeaker or headphones?",
    "Do you know where we live?",
    "Do you like applesauce?",
    "Do you like ginger cookies?",
    "Do you like oatmeal?",
    "Do you like onions?",
    "Do you like pancakes?",
    "Do you like raw oysters?",
    "Do you like soybeans?",
    "Do you like whole wheat bread?",
    "Do you live nearby?",
    "Do you play ball?",
    "Do you remember the story about the gingerbread boy?",
    "Do you see the searchlight?",
    "Do you shop downtown?",
    "Do you think it will rain?",
    "Drive on the right side",
    "Eggplant is a vegetable",
    "Everyone went home at noon",
    "Father's bookmark is blue",
    "Fathers watch is fast",
    "Fathers watch is old",
    "Fathers watch is wrong",
    "Father employs four men",
    "Father fixed the blowout",
    "Father gave me a wrist watch",
    "Father has brown shoes",
    "Father is in fine health again",
    "Father is in the car",
    "Father is reading in the den",
    "Father set the mousetrap",
    "Football is a fast game",
    "Gold was discovered in Alaska in 1900",
    "Goodbye",
    "Go to the head of the line",
    "Green is a cool color",
    "Handmade articles are expensive",
    "Hang the picture on the wall",
    "Happy New Year",
    "Have you change for a dime?",
    "Have you drunk your coffee?",
    "Have you ever been to South America?",
    "Have you ever seen such a large ship?",
    "Have you made any headway with the work?",
    "Have you packed your trunk?",
    "Have you read the morning paper?",
    "Have you read the newspaper?",
    "Have you seen father?",
    "Here are some flowers from the greenhouse",
    "Her name is not familiar",
    "He has a big head",
    "He has a good speaking voice",
    "He has a loud voice",
    "His face is familiar to me",
    "His phone number is easy to remember",
    "His shirt is blue",
    "Hot dogs are ten cents",
    "How did you cut your hand?",
    "How did you search for me?",
    "How do fish breathe?",
    "How high is the mountain?",
    "How large is the blackboard?",
    "How many bathrooms are there?",
    "How many home runs were there?",
    "How many men does your father employ?",
    "How many years did you live in California?",
    "How much does the roast weigh?",
    "How much is four and five?",
    "How much is one and eight?",
    "How much is one and four?",
    "How much is seven and two?",
    "How much is six and nine?",
    "How much was the pound of butter?",
    "How would you like the eggs cooked?",
    "I'll meet you at noon for lunch",
    "I'll see you at eight o'clock",
    "I'll see you later",
    "I'll write you a note from home",
    "Invite both of them to come",
    "In what state is the Grand Canyon?",
    "Is it safe to swim in the river?",
    "Is she your teacher?",
    "Is that a gold pin?",
    "Is that a palm tree?",
    "Is that a silver teaspoon?",
    "Is that his hat?",
    "Is the cake homemade?",
    "Is the guest room ready?",
    "Is the yellow house yours?",
    "Is your blouse handmade?",
    "Is your mother at home?",
    "Is your watch gold?",
    "It's ten o'clock",
    "It's time to leave",
    "It is a small world",
    "It is cold outside",
    "It is cool in the shade",
    "It is hard to say goodbye",
    "It is hot this afternoon",
    "It is one o'clock",
    "It is wise to think first and then speak",
    "It turned cold in the night",
    "It was very cold last night",
    "It was very warm yesterday",
    "I always enjoy the theatre",
    "I always read the morning newspaper",
    "I always use a cookbook",
    "I am as busy as a bee today",
    "I am going out of town",
    "I am going to dye my hair",
    "I am going to the store",
    "I am not familiar with that poem",
    "I bathe in the bathtub",
    "I bought a dust pan and brush",
    "I bought a head of lettuce",
    "I bought some apple jelly at the store",
    "I bought some blue yarn",
    "I bought this at the cut rate drug store",
    "I can't keep up with you",
    "I can't tell you why I said that",
    "I can't think of a thing to say",
    "I comb my hair",
    "I cut my finger",
    "I didn't get any mail today",
    "I did not join either club",
    "I don't care which one we see",
    "I don't know when I will get back",
    "I don't know where it is",
    "I don't like oatmeal",
    "I do not care for any ice cream",
    "I do not care to go",
    "I do not know what you want",
    "I do not like loud noises",
    "I eat the apple",
    "I enjoyed the game",
    "I enjoy singing old songs",
    "I forgot the address",
    "I forgot the boy's name",
    "I found a dime on the sidewalk",
    "I found a dime on the street",
    "I gave my check to the landlady",
    "I gave them some water",
    "I got the wrong number",
    "I go to school everyday",
    "I hate to say goodbye",
    "I have a hot dog",
    "I have a new black coat",
    "I have a new brown suit",
    "I have a new green car",
    "I have a new safe in my office",
    "I have a raincoat and an umbrella",
    "I have a red raincoat",
    "I have a rowboat",
    "I have four airplanes",
    "I have four shoes",
    "I have heard that song before",
    "I have lived in this apartment for four years",
    "I have lost my bookmark",
    "I have made some headway with it",
    "I have moved downtown",
    "I have no change",
    "I have one ball",
    "I have one bathtub",
    "I have one car",
    "I have seven cents",
    "I have three books",
    "I have three raincoats",
    "I have two apples",
    "I have two lamps",
    "I heard a loud noise",
    "I heard something",
    "I heard the bees buzzing",
    "I heard the clock strike midnight",
    "I heard the news on the radio",
    "I heard your voice in the hall",
    "I light the lamp",
    "I like football",
    "I like hot weather",
    "I like Ivory soap",
    "I like oyster stew",
    "I like that tune",
    "I like the taste of ginger",
    "I like to dance the jig",
    "I like to sing",
    "I like to sit here and sew",
    "I like to sit in the sun",
    "I like whole wheat bread",
    "I like your black coat",
    "I like your new dress",
    "I like your wallpaper",
    "I live near you",
    "I made a New Year's resolution",
    "I need new ties for my shoes",
    "I rang the bell twice",
    "I read the book",
    "I ride in the airplane",
    "I ride the bus",
    "I said goodbye",
    "I said goodbye to my family",
    "I saw a good movie",
    "I saw something funny today",
    "I saw them last night",
    "I saw you last night",
    "I see eight tables",
    "I see five lamps",
    "I see nine apples",
    "I see seven chairs",
    "I see six flowers",
    "I sit on the chair",
    "I smell fish",
    "I smell the flower",
    "I think I'll run along",
    "I think it is going to snow",
    "I think you are right",
    "I thought it was four o'clock",
    "I thought I heard a noise",
    "I thought you would never come",
    "I throw the ball",
    "I tied the package with string",
    "I try to save some money every month",
    "I value your friendship",
    "I walked downtown",
    "I want a good book to read",
    "I want some grape juice",
    "I want to go around the world",
    "I want to go home",
    "I wash with soap",
    "I was born in the South",
    "I wear the raincoat",
    "I will be a few minutes late",
    "I will go too",
    "I will go with you",
    "I will have hot tea with lemon",
    "I will leave the book for you to read",
    "I will pay your car fare",
    "I will take a walk while you are working",
    "I will wash the windshield",
    "I woke up at daybreak",
    "I write with the pencil",
    "I wrote on the blackboard",
    "Jack up the car",
    "June is a summer month",
    "June is the month of roses",
    "Leave a note for the milkman",
    "Leave everything as it is",
    "Leave your hat on the table",
    "Let's get a hot dog",
    "Let's paint the chairs yellow",
    "Let's play horseshoes",
    "Let's take a walk in the moonlight",
    "Let's take a walk in the park",
    "Let's take the afternoon off",
    "Let's take the shortcut home",
    "Let the dog out",
    "Make a note of the appointment",
    "Make up your mind",
    "Make yourself useful",
    "March in time with the music",
    "May I borrow your suitcase?",
    "May I have a few grapes?",
    "May I have some gingerbread?",
    "May I wash my hands?",
    "Mother's shoes are black",
    "Mothers watch is new",
    "Mothers watch is right",
    "Mothers watch is slow",
    "Mother fell down the steps",
    "Mother forgot to wake me up",
    "Mother has a headache",
    "Mother makes wonderful pancakes",
    "My brother's name is Jack",
    "My brother goes to law school",
    "My brother has two cars",
    "My brother is a mailman",
    "My brother is singing in the chorus",
    "My father is a lawyer",
    "My foot hurts",
    "My friend came to say goodbye",
    "My friend will be here soon",
    "My grandfather is very old",
    "My hands are dirty",
    "My home is in New York",
    "My home is in the South",
    "My new shoes are black",
    "My room is on the second floor",
    "My sister is a redhead",
    "My sister sings in the church choir",
    "My watch is slow",
    "My wristwatch is new",
    "My wrist is tired",
    "My wrist watch is new",
    "Nail the horseshoe over the doorway",
    "Next Sunday is Palm Sunday",
    "No thank you",
    "Of what use is this broken chair?",
    "Onion adds flavor to food",
    "Our ancestors used oil lamps",
    "Our doormat is brown",
    "Our lawyer won the case",
    "Our life span is becoming longer all the time",
    "Our rowboat has been painted yellow",
    "Our tire had a blowout",
    "Please boil the water",
    "Please buy a mousetrap",
    "Please buy a newspaper",
    "Please buy a pound of coffee",
    "Please buy some apples",
    "Please buy some heavy string",
    "Please buy some soap flakes",
    "Please buy whole wheat bread",
    "Please come again",
    "Please cut the pie",
    "Please do me a favor",
    "Please give me both letters",
    "Please hand me a spoon",
    "Please join me for supper",
    "Please let me carry your packages",
    "Please light the fire",
    "Please make a pie",
    "Please measure the length of the window",
    "Please ring the doorbell",
    "Please save the morning paper for me",
    "Please show me the way",
    "Please tie my shoe",
    "Please turn on the lamp",
    "Put some onion in the salad",
    "Put some wood on the fire",
    "Put the chair near the window",
    "Put the dish on the table",
    "Put the dog outside",
    "Put the dog out",
    "Put the ice cubes in the glass",
    "Put the match in the ashtray",
    "Put the soap flakes in the dish pan",
    "Put the spoon on the table",
    "Put the yellow flowers in the bowl",
    "Put your coats in the guest room",
    "Put your hat on your head",
    "Redheads are said to have fiery tempers",
    "Red is my favorite color",
    "Sails are usually made of canvas",
    "Shall I save this paper?",
    "Shall we boil the eggs?",
    "Shall we go out for dinner?",
    "Shall we have fish on Friday?",
    "Shall we walk home?",
    "She breathes with difficulty",
    "She has a red hat",
    "She isn't as young as she looks",
    "She is our new speech teacher",
    "She told us a sad story",
    "She will wash your shirts",
    "Shore leave has been cancelled",
    "Sit down on the sofa",
    "Sit in this chair",
    "Slow is an adverb",
    "Soap flakes are white",
    "Someone closed the door",
    "Something is better than nothing",
    "Something is wrong with the radio",
    "Sometimes we sit by the fireside",
    "Some animals eat hay",
    "Some verbs express action",
    "Southerners like cornbread",
    "Sunday at the zoo is always a busy day",
    "Take the ice cubes from the tray",
    "Take your time",
    "Tell me something about your family",
    "Thanksgiving comes on Thursday",
    "Thanksgiving day comes in November",
    "That's a fine picture of you",
    "That's a good idea",
    "That's news to me",
    "That is against the law",
    "That is an old song",
    "That is a beautiful flower",
    "That is a beautiful lamp shade",
    "That is a good book",
    "That is a pretty tune",
    "That is a very old law",
    "That man is drunk",
    "That song sounds familiar",
    "That tie looks well with your suit",
    "That was a fine show",
    "That was a good game",
    "That was the wrong thing to say",
    "Their friendship has lasted many years",
    "There are flowers on the wallpaper",
    "There are four goldfish in the bowl",
    "There are no flowers on the bush",
    "There is a beautiful sunset",
    "There is a crack in the teapot",
    "There is a radio in the schoolroom",
    "There is a rose on the bush",
    "There is a searchlight in the sky",
    "There is a verb in every sentence",
    "There is dust on the table",
    "There is no adverb in the phrase",
    "There is no view from my window",
    "There were many cars on the turnpike",
    "These are my shoes",
    "These gloves are too large",
    "These shoes are too large",
    "These snowballs are too soft",
    "They have a large fireplace",
    "The airplane is blue",
    "The airplane is yellow",
    "The apple is red",
    "The apple is yellow",
    "The ball game is at two o'clock",
    "The ball is blue and white",
    "The ball is blue",
    "The ball is yellow",
    "The bathroom is on the first floor",
    "The bathtub is pink",
    "The bathtub is white",
    "The beehive has twenty thousand bees",
    "The bell is loud",
    "The birds began to chirp at daybreak",
    "The blackboard is too small",
    "The blackboard needs washing",
    "The blackout was enforced during the war",
    "The black widow spider is dangerous",
    "The blowout damaged the tire",
    "The blowout made a loud noise",
    "The boat is easy to row",
    "The boat is late",
    "The boat was an hour late",
    "The bookcase is under the window",
    "The bookkeeper is away",
    "The book cost three dollars",
    "The book is long",
    "The book is red",
    "The book is yellow",
    "The boys are playing ball",
    "The boys are throwing snowballs",
    "The boys like to march",
    "The boys made a playhouse",
    "The boys make so much noise",
    "The boys were busy as bees",
    "The boy caught a jellyfish",
    "The boy has a large head",
    "The boy is five years old",
    "The boy is happy and carefree",
    "The boy laughed",
    "The boy said hello",
    "The boy waved his hand",
    "The boy went up the stairs",
    "The buses are crowded during the rush hour",
    "The bus doesn't stop here",
    "The bus is late",
    "The bus stop is over there",
    "The butter was cut in cubes",
    "The car fare is ten cents",
    "The car is at the door",
    "The car is outside",
    "The cat caught a mouse",
    "The chair is green",
    "The chair is purple",
    "The children are on the seesaw",
    "The children are playing Jack in the box",
    "The children are playing on the seesaw",
    "The child is five years old",
    "The child is too young to go to school",
    "The child tore a leaf from the book",
    "The Chinese raise soybeans",
    "The church bell rang at eleven o'clock",
    "The church is old",
    "The church is on the southeast corner",
    "The coffee is too hot",
    "The comb is brown",
    "The comb is gray",
    "The cookbook is on the table",
    "The cook is in the kitchen",
    "The cowboy lives on the ranch",
    "The cowboy wore a large hat",
    "The cow is brown",
    "The cow is in the barn",
    "The day was hot",
    "The dictionary is a useful book",
    "The dish is broken",
    "The dish pan is too small",
    "The doctor was called over the loudspeaker",
    "The dog does not belong to us",
    "The dog has sad eyes",
    "The doorbell is out of order",
    "The dust pan is in the kitchen",
    "The earthquake killed many people",
    "The earth is a planet",
    "The earth is round",
    "The farmer has a beehive",
    "The farmer has a Jersey cow",
    "The farmer has a large haystack",
    "The farmer is bringing us vegetables tomorrow",
    "The farmer is planting wheat",
    "The ferry boat was very crowded",
    "The fireplace is made of stone",
    "The flagpole is high",
    "The flagpole is on top of the building",
    "The flag is red, white, and blue",
    "The flag was raised at sunrise",
    "The flower is green",
    "The flower is purple",
    "The food at that restaurant is very good",
    "The girl cried",
    "The girl said goodbye",
    "The girl went down the stairs",
    "The glass left a mark on the table",
    "The glove belongs to me",
    "The goldfish are in the bowl",
    "The guests have arrived",
    "The guest room is large",
    "The gypsy read my palm",
    "The hay is in the barn",
    "The highway has many sign boards",
    "The highway is narrow",
    "The highway number is 45",
    "The highway runs north and south",
    "The hillside was covered with daisies",
    "The horse eats hay",
    "The house has a side porch",
    "The ice cream is orange",
    "The ice cream is white",
    "The jellyfish is not good to eat",
    "The jig is an old fashioned dance",
    "The juice of the lemon is sour",
    "The June bug can fly",
    "The June bug is a brown beetle",
    "The king has limited power",
    "The kitchen is on the first floor",
    "The lamp is on the table",
    "The lamp is orange",
    "The lamp is white",
    "The lamp shade is green",
    "The lamp shade is made of glass",
    "The lamp shade needs cleaning",
    "The landlady is having my apartment painted",
    "The landlady lives on the first floor",
    "The length of the room is twenty feet",
    "The lion is in his den",
    "The machine won't run",
    "The mailman is late this morning",
    "The man died and left a will",
    "The matchbox is in the kitchen",
    "The matchbox is on the table",
    "The mats need washing",
    "The milkman is late today",
    "The moonlight is beautiful",
    "The moonlight is bright",
    "The moon is full tonight",
    "The mountain is 9000 feet high",
    "The mountain is very high",
    "The mousetrap is in the kitchen",
    "The night was cold",
    "The night was dark",
    "The oysters are large",
    "The palm trees are tall",
    "The park is beautiful in spring",
    "The plan does not suit me",
    "The playhouse is in the yard",
    "The policeman searched for the car",
    "The postman rang the bell",
    "The pound cake is for dessert",
    "The pound cake is very good",
    "The price of the house is too high",
    "The radio program is bringing us news of the day",
    "The raincoat is black",
    "The raincoat is tan",
    "The rain is good for the farmer's crops",
    "The rosebush needs to be sprayed",
    "The rowboat is mine",
    "The sailboat is small",
    "The sailboat is white",
    "The sailors are on shore leave",
    "The schoolroom is bright and airy",
    "The schoolroom is too small",
    "The seesaw goes up and down",
    "The ship will sail next Thursday",
    "The shoe is black",
    "The shoe is tan",
    "The sidewalk is narrow",
    "The sidewalk is wide",
    "The sign board was very large",
    "The sign said stop",
    "The sign was small",
    "The snow is white",
    "The snow on the trees is beautiful",
    "The soap is in the bathroom",
    "The soap is pink",
    "The soap is white",
    "The soap is yellow",
    "The soap smells good",
    "The soldiers carried the flag",
    "The soldiers march in the parade",
    "The soybean is a useful food",
    "The spoon is very old",
    "The stop sign is black and yellow",
    "The stop sign is large",
    "The streets were very dark during the blackout",
    "The sunset was red and orange",
    "The sun is hot",
    "The sun is hot today",
    "The sun is shining",
    "The sweater was made of heavy yarn",
    "The table is a foot wide",
    "The table is brown",
    "The table is gray",
    "The tax on this is six cents",
    "The teacher is a young woman",
    "The teacher is very efficient",
    "The teacher went to the circus with the children",
    "The teapot is on the table",
    "The tea is cold",
    "The tray holds twelve ice cubes",
    "The trunk is heavy",
    "The turnpike is new",
    "The turnpike is wide",
    "The United Nations is trying to insure the peace",
    "The view from the hill is lovely",
    "The view from the top of the hill was lovely",
    "The weather is bad",
    "The weather man says rain",
    "The whistle blew at twelve o'clock",
    "The windshield is dirty",
    "The wind blew the tree down",
    "The wind is blowing from the southeast",
    "The wind is blowing hard",
    "The wind is cold",
    "The wind will blow our hats off",
    "The woman is afraid of the mouse",
    "The woodwork is white in our house",
    "The workmen went home when the whistle blew",
    "The young man is very tall",
    "This book is useful",
    "This bread is not fresh",
    "This cord is of no use",
    "This elevator goes down",
    "This hat is the wrong head size",
    "This homemade pie is very good",
    "This is a large nation",
    "This is a leaf from the maple tree",
    "This is zone six",
    "This row is reserved",
    "This teaspoon belonged to my mother",
    "Those boys are brothers",
    "Throw the ball to me",
    "To whom does this glove belong?",
    "Turn on the lamp",
    "Turn to the right",
    "Was it a good movie?",
    "Watch your step",
    "We'll have to rush to catch the bus",
    "Wear a hat to shade your eyes",
    "Were you at home last night?",
    "We advertised for a bookkeeper",
    "We are going to the theatre tonight",
    "We came home at midnight",
    "We can take the trunk in the taxi",
    "We crossed the river on the ferry",
    "We drove beyond the turn",
    "We drove through the park",
    "We enjoyed the play",
    "We felt the earthquake",
    "We found a jellyfish in the water",
    "We gathered flowers along the hillside?",
    "We got home at midnight",
    "We got off at the wrong station",
    "We had applesauce for lunch",
    "We had a carefree holiday",
    "We had a good view of the canyon from the airplane",
    "We had a large meal",
    "We had oatmeal for breakfast",
    "We have a grape vine in our yard",
    "We have a holiday on Thanksgiving",
    "We have a new doormat",
    "We have a sailboat",
    "We have a view of the river from our windows",
    "We have employed a good lawyer",
    "We have had bad weather lately",
    "We heard a loud noise upstairs",
    "We invited four guests",
    "We kept the cat away from the goldfish",
    "We lay on the beach in the sun",
    "We like ice cold grape juice",
    "We live in the temperate zone",
    "We live near a good school",
    "We live on the earth",
    "We made the wrong turn",
    "We need a new lamp",
    "We picked enough grapes to make jelly",
    "We rented a rowboat for the afternoon",
    "We sat in the front row at church",
    "We sat in the shade to cool off",
    "We saw some zebras at the zoo",
    "We saw the midnight show",
    "We saw the sunset from the hill",
    "We saw the white boat",
    "We saw you at the movie",
    "We searched for you everywhere",
    "We took a long walk",
    "We took a shortcut to the movies",
    "We watched the sunset",
    "We went beyond the sign",
    "We went to a nearby restaurant",
    "We went to the beach yesterday",
    "We went to the theatre last night",
    "We went to the zoo",
    "What's the news in the paper?",
    "What's the news?",
    "What a dark day",
    "What color is your car?",
    "What color shall we paint the wall?",
    "What color woodwork do you have?",
    "What color yarn shall I use?",
    "What day is this?",
    "What did grandfather say?",
    "What did you say?",
    "What did you see at the theatre?",
    "What do you take for a headache?",
    "What head size is your hat?",
    "What is a verb?",
    "What is that noise?",
    "What is that thing on the table?",
    "What is the highway number?",
    "What is the length of your coat?",
    "What is the name of that man?",
    "What is the name of the ship?",
    "What is the number of the highway?",
    "What is your friend's name?",
    "What is your name?",
    "What is your postal zone number?",
    "What kind of bush is that?",
    "What kind of fish is that?",
    "What movie did you see?",
    "What shall we do?",
    "What shape is the beehive?",
    "What size shirt does he wear?",
    "What this country needs is a good five cent cigar",
    "What time does the mailman come?",
    "What time does your train leave?",
    "What time is it?",
    "What time is the ball game?",
    "What was the name of the play?",
    "Wheat is called the staff of life",
    "When are you going away?",
    "When did your dog die?",
    "When did you buy your car?",
    "When did you go?",
    "When did you see them?",
    "When will I see you again?",
    "When will the boat sail?",
    "When will the bus arrive?",
    "When will you come?",
    "When will you get back?",
    "Where are the balls?",
    "Where are the flowers?",
    "Where are your friends?",
    "Where are you employed?",
    "Where are you going this afternoon?",
    "Where did you buy your shoes?",
    "Where does all the dust come from?",
    "Where do you keep the cards?",
    "Where do you keep the dog?",
    "Where in the world have you been?",
    "Where is father's saw?",
    "Where is mother?",
    "Where is my hat?",
    "Where is my notebook?",
    "Where is my red bathrobe?",
    "Where is the boat?",
    "Where is the boy?",
    "Where is the car?",
    "Where is the fire?",
    "Where is the law school?",
    "Where is the matchbox?",
    "Where is the stop sign?",
    "Where is your home?",
    "Where is your room?",
    "Where is your wristwatch?",
    "Which bus shall we take?",
    "Which club did you join?",
    "Which house is yours?",
    "Which is new?",
    "Which is old?",
    "Which is right?",
    "Which is wrong?",
    "Which law school does he go to?",
    "Which one do you want?",
    "Which play shall we see?",
    "Which suitcase would you like?",
    "Which wallpaper did you choose?",
    "Which way shall we walk?",
    "Whole wheat bread is healthful",
    "Whose book is that?",
    "Whose car is that?",
    "Whose name was called?",
    "Whose pencils are these?",
    "Whose radio do I hear?",
    "Who is at the door?",
    "Who is going to win?",
    "Who is going with you?",
    "Who is in the airplane?",
    "Who is in the car?",
    "Who is in the kitchen?",
    "Who is on the radio?",
    "Who is singing on the radio?",
    "Who is that man?",
    "Who rang the bell?",
    "Why are you late?",
    "Why are you sad?",
    "Why did you call me?",
    "Why did you cry?",
    "Why did you laugh?",
    "Why did you say goodbye?",
    "Why did you say hello?",
    "Why did you say no?",
    "Why did you say yes?",
    "Why don't you drink your juice?",
    "Will you buy some bread?",
    "Will you close the door?",
    "Will you come to our party on New Year's Eve?",
    "Will you cut some wood?",
    "Will you cut the bread for me?",
    "Will you cut the cake?",
    "Will you dust the table?",
    "Will you have a dish of ice cream?",
    "Will you have a glass of grape juice?",
    "Will you have iced tea or hot tea?",
    "Will you let me help you?",
    "Will you light the lamp?",
    "Will you mail this letter for me?",
    "Will you make a pound cake?",
    "Will you make some applesauce?",
    "Will you sew a button on my shirt?",
    "Will you sing for us?",
    "Will you watch the baby?",
    "Wipe your feet on the doormat",
    "Write your name on the blackboard",
    "Yellow and green look well together",
    "Yesterday was the first of the month",
    "Yes thank you",
    "Your black hat is very becoming",
    "Your homework is on the blackboard",
    "Your makeup is very dark",
    "Your notebook is on the table",
    "You can't win all the time",
    "You can save money at cut rate stores",
    "You have the wrong number",
    "You may keep the letter",
    "You were away a long while",
]
